const express = require('express');
const swaggerUi = require('swagger-ui-express');
const swaggerSpec = require('./config/swagger');
const orderRoutes = require('./routes/orders.routes');
const errorMiddleware = require('./middlewares/error.middleware');
const app = express();
app.use(express.json());
app.use('/api/v1/orders', orderRoutes);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use(errorMiddleware);
module.exports = app;